pipeline {
    agent any

    triggers {
        githubPush()
        triggers { pollSCM('H */1 * * *') }
    }

    environment {
        VAR_NAME = 'Tecylab DevOps'
    }

    stages {
        stage('Hello') {
            steps {
                echo "Hello ${VAR_NAME}"
            }
        }

        stage('Environment') {
            steps {
                sh 'whoami'
                sh 'hostname'
                sh 'date'
                sh 'uptime'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
        always {
            echo 'Pipeline finished.'
        }
    }
}
